"""Qrels, adjudication, active sampling, and trust audit tools."""

from retrieval_lab.qrels.calibration import DEFAULT_JUDGE_CALIBRATION_REPORT, judge_calibration_command, judge_calibration_summary
from retrieval_lab.qrels.service import (
    active_qrels_samples,
    bootstrap_grade,
    bootstrap_qrels_from_rows,
    canonical_stage,
    load_qrels,
    merge_adjudicated_qrels,
    pooled_qrels_from_run_rows,
    pooled_qrels_summary,
    qrel_confidence,
    qrel_has_vote_conflict,
    qrel_needs_adjudication,
    qrel_relevance_vote,
    qrel_vote_judge_type,
    reranker_candidate_summary,
    qrels_audit_summary,
    qrels_trust_level,
    result_stage,
    validate_qrel,
    write_qrels,
)

__all__ = [
    "DEFAULT_JUDGE_CALIBRATION_REPORT",
    "active_qrels_samples",
    "bootstrap_grade",
    "bootstrap_qrels_from_rows",
    "canonical_stage",
    "judge_calibration_command",
    "judge_calibration_summary",
    "load_qrels",
    "merge_adjudicated_qrels",
    "pooled_qrels_from_run_rows",
    "pooled_qrels_summary",
    "qrel_confidence",
    "qrel_has_vote_conflict",
    "qrel_needs_adjudication",
    "qrel_relevance_vote",
    "qrel_vote_judge_type",
    "reranker_candidate_summary",
    "qrels_audit_summary",
    "qrels_trust_level",
    "result_stage",
    "validate_qrel",
    "write_qrels",
]
